site_name: Arduino LoRaWAN MAC in C (LMIC)

repo_url: https://github.com/mcci-catena/arduino-lmic
repo_name: mcci-catena/arduino-lmic

theme:
  name: material

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - "Overview":
      - "README": "index.md"
      - "Adding Regions": "howto-add-region.md"
  - "Technical Specification":
      - "technical-specification/introduction.md"
      - "Programming Model and API":
          - "technical-specification/programming-model-and-api/index.md"
          - "technical-specification/programming-model-and-api/run-time-functions.md"
          - "technical-specification/programming-model-and-api/application-callbacks.md"
          - "technical-specification/programming-model-and-api/the-lmic-struct.md"
          - "technical-specification/programming-model-and-api/api-functions.md"
      - "technical-specification/hal.md"
      - "technical-specification/examples.md"
      - "Product Information": "technical-specification/index.md"
      - "technical-specification/release-history.md"
